### ISSUE TITLE
Fragments

### ISSUE THREAD

**Issue by kacpersaw** [Plastix/Kotlin-Android-Boilerplate#11]
Hi,
Could you add sample of multiple fragments in one activity?

**Comment by Plastix** [comment]
Hey!

What are you curious about? Are you having trouble applying the MVP pattern to a multi-fragment activity? Is it Kotlin?

**Comment by kacpersaw** [comment]
Yes. I want to use MaterialDrawer. So i need multi-fragment activity and i don't know how implement this in your boilerplate

**Comment by Plastix** [comment]
I'm not a huge fan of Fragments so I tend to avoid them when I can. 

If you really need Fragments to implement your navigation drawer here is what I would probably do:
1. Implement the navigation drawer in the enclosing parent Activity.
2. Make a `Presenter` for each Fragment and use `PresenterFragment` from this project as the abstract Fragment base class.
3. If your parent Activity has more complicated logic than just Fragment transactions consider adding a presenter for Activity logic as well (thus use `PresenterActivity`).
4. Use your preferred method of inter-fragment/activity communication (Interfaces/Event buses/RxJava?). 

Remember that the point of the MVP pattern is just to abstract away normal Java business logic so that it is easier to test. If our logic doesn't depend on Android framework resources then we don't need to simulate (Robolectric) or run the OS (Android Emulator) to test our code, meaning faster tests.

**Comment by kacpersaw** [comment]
Why you prefer activities? I'm new to this mvp-thing with rx etc. You think that activity per page is better than fragments? As I understand it, I can create drawer instance in base `PresenterActivity`?

**Comment by Plastix** [comment]
Everyone complains about the [Fragment lifecycle](https://developer.android.com/guide/components/fragments.html#Lifecycle) being too complex. Although it is pretty well documented, I still find it tough to understand completely. I'd just rather prefer to pass explicit intents to open Activities than create Fragment transactions. It can also be really tricky to get Fragments right depending on how you decide to use them.

You might want to read through this Reddit thread: https://www.reddit.com/r/androiddev/comments/53ca54/fragments_what_are_they_good_for/

**Comment by kacpersaw** [comment]
Okay, I think that Activities can be better for my app. So what is the best method to implement drawer instance to all activities without one (`LoginActivity`). Should I create new Base `PresenterActivity` and add drawer instance to it and after that extend this class to my acitivites where I want to have drawer?

**Comment by Plastix** [comment]
Don't let me talk you into avoiding Fragments! Do what works for your app and the problem you are trying to solve.

A base Activity class with drawer functionality is one way to go about it.  However, the famous OOP principle states "[Favor composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance)". 

A more idiomatic Kotlin approach would be to use Mixins by taking advantage of [multiple inheritance using interfaces](https://kotlinlang.org/docs/reference/interfaces.html). This way you could implement your drawer functionality in an interface and have your Activity class "implement" it  (as well as extending from the base `PresenterActivity`). Here is a short article on Mixins in Kotlin: http://codemonkeyism.com/exploring-delegation-in-kotlin/

I'd also recommend reading this great article on Java 8 Mixins (using default interfaces) which works very similar to the way Kotlin does it: http://hannesdorfmann.com/android/java-mixins.
