### ISSUE TITLE
Issue using PresenterFragment

### ISSUE THREAD

**Issue by tehras** [Plastix/Kotlin-Android-Boilerplate#7]
Hey,
I'm trying to extend PresenterFragment to use like you do with Activites,
however, i'm getting an issue:

```
kotlin.UninitializedPropertyAccessException: lateinit property presenterLoaderProvider has not been initialized
                                                                                       at com.github.tehras.loanapplication.ui.base.PresenterFragment.onCreateLoader(PresenterFragment.kt:69)
```

Any ideas why this could be happening?

**Comment by Plastix** [comment]
Where are you trying to access the presenter?

**Comment by tehras** [comment]
It was getting called inside PresenterFragment which I'm extending from a fragment within an activity. Do i not need to inject it the same way as the activity?

**Comment by Plastix** [comment]
`PresenterFragment` uses the same injection setup as `PresenterActivity`. Subclassing the fragment will force you to implement `injectDependencies(...)` which will inject (and initialize) the `presenterLoaderProvider`. Make sure you are injecting and providing your dependencies correctly. 

Can you provide a simple code example?

**Comment by tehras** [comment]
Yep. So.
My AppComponent:
`@Singleton
@Component(modules = arrayOf(AppModule::class, NetworkModule::class, ApiModule::class))
interface AppComponent {

```
fun injectTo(app: MyApp)

// Submodule methods
// Every screen is its own submodule of the graph and must be added here.
// fun plus(module: Module): ModuleComponent
fun plus(homeLoanModule: HomeLoanModule): HomeLoanComponent

fun plus(homeSingleLoanModule: HomeLoanSingleModule): HomeLoanSingleComponent
```

}`

Then my Fragment Module is this:

```
@Module
class HomeLoanSingleModule(fragment: BottomSheetDialogFragment) : FragmentModule(fragment) {

    @Provides @FragmentScope
    fun providePresenter(presenter: HomeLoanSinglePresenter): HomeLoanSinglePresenter = presenter
}
```

and finally the fragment is injecting like this:

```
override fun injectDependencies(graph: AppComponent) {
        graph.plus(HomeLoanSingleModule(this))
                .injectTo(this)
    }

```

This causes cyclical dependency, and i have a feeling i have to inject to the Activiy's component?

**Comment by Plastix** [comment]
The problem is that you aren't providing your presenter correctly to your dependency graph.

You need something like this

``` Kotlin
// In HomeLoanSingleModule
 @Provides @FragmentScope
    fun providePresenter(presenter: HomeLoanSinglePresenterImpl): HomeLoanSinglePresenter = presenter
```

I do this because I have interfaces for my each of presenters:
`MyPresenter` (Interface)
`MyPresenterImpl` (Implemented presenter)

I have an `@Inject` constructor on `MyPresenterImpl` so Dagger knows how to create it. The line in the module tells Dagger to expose `MyPresenterImpl` as `MyPresenter`. `MyPresenter` ends up being the type injected into the Fragment/Activity.

If you don't have an interface for your presenter, just use an `@Inject` constructor and omit providing it from your module. I was making an interface for each presenter so that I could mock them using Mockito. Now that Mockito 2 can mock static and final classes, I don't really need all these interfaces anymore. I should get around to simplifying the interface boilerplate at some point.

**Comment by tehras** [comment]
Oh man, thanks so much. Dumbest mistake ever. Btw, trying to learn the MVP pattern and this code is really clean / very well separated.

**Comment by Plastix** [comment]
No problem. Glad I could help. 👍  I've definitely made similar mistakes.
