### ISSUE TITLE
Using Service

### ISSUE THREAD

**Issue by murselturk** [Plastix/Kotlin-Android-Boilerplate#8]
Hi,

I'm trying to learn Dagger 2 and MVP pattern and find this repo really clean. I want to use MediaPlayer and in DetailActivity and create also a Background Service. How should I implement Module or Component for this purpose?

Thanks

**Comment by Plastix** [comment]
Hello! Thanks for the question!

The way that this project is setup is that each screen of the app has its own submodule in the dependency graph.

For example, I have a `ListActivity` which has a corresponding `@Subcomponent ListComponent`. This subcomponent is responsible for injecting all dependencies to `ListActivity`. `ListComponent` pulls the list-specific dependencies from `ListModule`. In order for the `ListComponent` to be added to the graph it must be declared in the root graph component `ApplicationComponent`.  For example, ` fun plus(module: ListModule): ListComponent`. 

So if you have a `DetailActivity`, you can make a new subcomponent and module for the specific screen. If `MediaPlayer` and `SomeBackgroundService` are specific to `DetailActivity` you could provide them from `DetailActivity`'s module. Otherwise, you might want them in a different module.

Sorry for the late response.
